// <auto-generated />
using System;
using FitnessPathApp.DomainLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessPathApp.DomainLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230626152607_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseChoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<Guid>("TrainingLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseChoiceId");

                    b.HasIndex("TrainingLogId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("82a61b04-1cda-4045-abb5-0c1596f9aa36"),
                            ExerciseChoiceId = new Guid("3e165f3d-f9fa-4e27-a5b9-05d3b938d8eb"),
                            Reps = 5,
                            Sets = 5,
                            TrainingLogId = new Guid("cb31d06e-13da-4ba0-a923-5c062399f3a8"),
                            Weight = 100.0
                        },
                        new
                        {
                            Id = new Guid("46aa1ca5-4670-4a38-a840-96204dd0b3a2"),
                            ExerciseChoiceId = new Guid("bde86a6d-9a37-420d-93ca-60d7b02dc7c4"),
                            Reps = 5,
                            Sets = 5,
                            TrainingLogId = new Guid("cb31d06e-13da-4ba0-a923-5c062399f3a8"),
                            Weight = 140.0
                        },
                        new
                        {
                            Id = new Guid("853172d8-26ca-4de1-acc0-b28d753c328f"),
                            ExerciseChoiceId = new Guid("c1769344-dd80-41fe-bbfc-a16df832929b"),
                            Reps = 5,
                            Sets = 3,
                            TrainingLogId = new Guid("cb31d06e-13da-4ba0-a923-5c062399f3a8"),
                            Weight = 180.0
                        },
                        new
                        {
                            Id = new Guid("9d9d6825-98ba-47cf-b137-2f6431a047ca"),
                            ExerciseChoiceId = new Guid("c328e92b-33ff-4863-9397-d53424ca3f5c"),
                            Reps = 8,
                            Sets = 3,
                            TrainingLogId = new Guid("cb31d06e-13da-4ba0-a923-5c062399f3a8"),
                            Weight = 60.0
                        },
                        new
                        {
                            Id = new Guid("e937cea5-99db-4068-96a2-c75fde51df74"),
                            ExerciseChoiceId = new Guid("c328e92b-33ff-4863-9397-d53424ca3f5c"),
                            Reps = 8,
                            Sets = 3,
                            TrainingLogId = new Guid("cb31d06e-13da-4ba0-a923-5c062399f3a8"),
                            Weight = 70.0
                        });
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.ExerciseChoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExerciseType")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExerciseChoices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3e165f3d-f9fa-4e27-a5b9-05d3b938d8eb"),
                            ExerciseType = 1,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/04/barbell-bench-press.gif",
                            IsFavorite = true,
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = new Guid("bde86a6d-9a37-420d-93ca-60d7b02dc7c4"),
                            ExerciseType = 1,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/03/barbell-full-squat.gif",
                            IsFavorite = true,
                            Name = "Squat"
                        },
                        new
                        {
                            Id = new Guid("c1769344-dd80-41fe-bbfc-a16df832929b"),
                            ExerciseType = 1,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/02/barbell-deadlift-movement.gif",
                            IsFavorite = true,
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = new Guid("c328e92b-33ff-4863-9397-d53424ca3f5c"),
                            ExerciseType = 1,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/04/military-press.gif",
                            IsFavorite = true,
                            Name = "Overhead Press"
                        },
                        new
                        {
                            Id = new Guid("0b9a334e-0849-4a54-91bd-e6789bcab11c"),
                            ExerciseType = 1,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/08/barbell-bent-over-row.gif",
                            IsFavorite = true,
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = new Guid("e86748e9-9203-41a2-bdf3-12c9a0b24560"),
                            ExerciseType = 1,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/06/barbell-romanian-deadlift-movement.gif",
                            IsFavorite = true,
                            Name = "Romanian Deadlift"
                        },
                        new
                        {
                            Id = new Guid("032c5827-77d7-4f38-a205-2aea3a215005"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2021/11/dumbbell-romanian-deadlift.gif",
                            IsFavorite = true,
                            Name = "Dumbell Romanian Deadlift"
                        },
                        new
                        {
                            Id = new Guid("5020ad9b-2a1f-4634-99a6-f89b65b46ab4"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/11/straight-leg-deadlift.gif",
                            IsFavorite = true,
                            Name = "Stiff Leg Deadlift"
                        },
                        new
                        {
                            Id = new Guid("8ef4878b-2aa6-4319-bd84-abda5148fba2"),
                            ExerciseType = 1,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/11/pull-up.gif",
                            IsFavorite = true,
                            Name = "Pullup"
                        },
                        new
                        {
                            Id = new Guid("7b548a27-ecdf-4f15-b485-8f57e456d3f5"),
                            ExerciseType = 1,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/09/chin-ups.gif",
                            IsFavorite = true,
                            Name = "Chinup"
                        },
                        new
                        {
                            Id = new Guid("dd5a8953-4e8b-48c1-973a-741faaece2f7"),
                            ExerciseType = 1,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2023/03/neutral-grip-pull-ups-shoulder-width.gif",
                            IsFavorite = true,
                            Name = "Neutral Grip Pullup"
                        },
                        new
                        {
                            Id = new Guid("0c12a6c5-d47e-431c-91b0-8e8d9a6fa83a"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/08/cable-seated-row.gif",
                            IsFavorite = true,
                            Name = "Cable Row"
                        },
                        new
                        {
                            Id = new Guid("2e1c74ce-d121-4832-8530-d045b717c4e7"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/08/wide-grip-lat-pulldown.gif",
                            IsFavorite = true,
                            Name = "Lat Pulldown"
                        },
                        new
                        {
                            Id = new Guid("f856276a-e2ab-4158-bf50-0075197b7a16"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2021/10/single-arm-dumbbell-row.gif",
                            IsFavorite = true,
                            Name = "One Arm Dumbell Row"
                        },
                        new
                        {
                            Id = new Guid("1cea4155-1b12-4fec-9d31-1c91c3f6fb60"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/dumbbell-shoulder-press.gif",
                            IsFavorite = true,
                            Name = "Dumbell Shoulder Press"
                        },
                        new
                        {
                            Id = new Guid("a9bfc5a4-8666-47f0-ab14-929345675627"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/incline-dumbbell-curl.gif",
                            IsFavorite = true,
                            Name = "Incline Dumbell Curl"
                        },
                        new
                        {
                            Id = new Guid("dcc607b0-0573-4ba5-b00f-7db3525a8e04"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/03/dumbbell-bicep-curl.gif",
                            IsFavorite = true,
                            Name = "Dumbell Bicep Curl"
                        },
                        new
                        {
                            Id = new Guid("23af1cfe-de80-4a25-98f3-9de67f64cf36"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/03/ez-bar-preacher-curl.gif",
                            IsFavorite = true,
                            Name = "Ez Preacher Curl"
                        },
                        new
                        {
                            Id = new Guid("f8e9dcb1-3269-4b40-8a91-b5cc6c18211e"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/04/dumbbell-hammer-curl.gif",
                            IsFavorite = true,
                            Name = "Dumbell Hammer Curl"
                        },
                        new
                        {
                            Id = new Guid("44eb78e8-1353-41e2-ba3d-0b93c4c66af5"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/03/dumbbell-concentration-curl.gif",
                            IsFavorite = true,
                            Name = "Dumbell Concentration Curl"
                        },
                        new
                        {
                            Id = new Guid("9e78421c-e5f8-4040-a0fd-8a12454b03bc"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2023/02/ez-bar-bicep-curl.gif",
                            IsFavorite = true,
                            Name = "Ez Bar Curl"
                        },
                        new
                        {
                            Id = new Guid("828ac5f9-1936-4194-a462-e83163f12162"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/05/barbell-curl.gif",
                            IsFavorite = true,
                            Name = "Barbell Curl"
                        },
                        new
                        {
                            Id = new Guid("c1258b52-4e63-4aa7-a075-a16f4a460357"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/08/dumbbell-chest-fly-muscles.gif",
                            IsFavorite = true,
                            Name = "Dumbell Chest Fly"
                        },
                        new
                        {
                            Id = new Guid("82f28e0d-b7cf-4c9a-98b9-9b757b31212c"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/09/dumbbell-chest-press.gif",
                            IsFavorite = true,
                            Name = "Dumbell Chest Press"
                        },
                        new
                        {
                            Id = new Guid("be5d2cee-e898-4b3a-8386-ea39fda3622e"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/09/dumbbell-incline-chest-press.gif",
                            IsFavorite = true,
                            Name = "Dumbell Incline Press"
                        },
                        new
                        {
                            Id = new Guid("4e24fd67-6d30-433b-a604-d01ad90ef54e"),
                            ExerciseType = 1,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/05/incline-barbell-bench-press.gif",
                            IsFavorite = true,
                            Name = "Incline Bench Press"
                        },
                        new
                        {
                            Id = new Guid("5c9d00b3-8095-4a75-8d83-98d5132d4db3"),
                            ExerciseType = 1,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/close-grip-bench-press-movement.gif",
                            IsFavorite = true,
                            Name = "Close Grip Bench Press"
                        },
                        new
                        {
                            Id = new Guid("4e47994a-3b58-47b6-b4ac-424a6686cd36"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/08/flat-bench-skull-crusher.gif",
                            IsFavorite = true,
                            Name = "Skullcrusher"
                        },
                        new
                        {
                            Id = new Guid("4f6cfebb-012b-45df-a565-ae3939d74d26"),
                            ExerciseType = 1,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2021/08/diamond-push-up.gif",
                            IsFavorite = true,
                            Name = "Diamond Pushup"
                        },
                        new
                        {
                            Id = new Guid("e006abf7-da50-4530-a93d-8683fed79d43"),
                            ExerciseType = 1,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/11/push-up.gif",
                            IsFavorite = true,
                            Name = "Pushup"
                        },
                        new
                        {
                            Id = new Guid("a847047f-4af5-444e-a81e-ebacd4097aae"),
                            ExerciseType = 1,
                            ImageUrl = "https://fitnessprogramer.com/wp-content/uploads/2021/05/Dumbbell-Bulgarian-Split-Squat.gif",
                            IsFavorite = true,
                            Name = "Bulgarian Split Squat"
                        },
                        new
                        {
                            Id = new Guid("60669c8a-df74-4e95-a9ce-c9b7e0be40ab"),
                            ExerciseType = 1,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/dumbbell-lunges.gif",
                            IsFavorite = true,
                            Name = "Lunges"
                        },
                        new
                        {
                            Id = new Guid("d6350d47-6274-47be-a43c-ecdf29cf7390"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/03/tricep-overhead-extensions.gif",
                            IsFavorite = true,
                            Name = "Triceps Overhead Extension"
                        },
                        new
                        {
                            Id = new Guid("c3449838-8c95-400a-823f-f06e49618269"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2021/10/cable-tricep-pushdown.gif",
                            IsFavorite = true,
                            Name = "Cable Triceps Pushdown"
                        },
                        new
                        {
                            Id = new Guid("1b5889fa-484c-4a55-8df7-7b38415762c2"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/03/dumbbell-lateral-raise.gif",
                            IsFavorite = true,
                            Name = "Dumbell Lateral Raise"
                        },
                        new
                        {
                            Id = new Guid("2607d5fe-bcb6-48e7-a2ed-6ff0693f2361"),
                            ExerciseType = 1,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/09/barbell-hip-thrust.gif",
                            IsFavorite = true,
                            Name = "Hipthrust"
                        },
                        new
                        {
                            Id = new Guid("dd4d5068-0311-4189-b7a4-237bf43306fb"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/10/barbell-reverse-curl.gif",
                            IsFavorite = true,
                            Name = "Barbell Reverse Curl"
                        },
                        new
                        {
                            Id = new Guid("46102532-02a6-4e62-b35b-bcea221b77c1"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/plank-movement.gif",
                            IsFavorite = true,
                            Name = "Plank"
                        },
                        new
                        {
                            Id = new Guid("18522a6b-c3c0-454e-bc25-d145fb69d0ad"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/05/decline-sit-up.gif",
                            IsFavorite = true,
                            Name = "Decline Situp"
                        },
                        new
                        {
                            Id = new Guid("a34f4863-35ee-4baf-86c8-d2a678bc1776"),
                            ExerciseType = 2,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/06/hanging-leg-raise-movement.gif",
                            IsFavorite = true,
                            Name = "Hanging Leg Raises"
                        },
                        new
                        {
                            Id = new Guid("1c4e0b57-e66a-4604-960b-122c396b1574"),
                            ExerciseType = 1,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/04/weighted-dips.gif",
                            IsFavorite = true,
                            Name = "Weighted Dips"
                        },
                        new
                        {
                            Id = new Guid("846df523-dc1d-4206-917c-7b289e156ccc"),
                            ExerciseType = 1,
                            ImageUrl = "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/chest-dip-movement.gif",
                            IsFavorite = true,
                            Name = "Dips"
                        });
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.FoodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<int>("Carbs")
                        .HasColumnType("int");

                    b.Property<int>("Fat")
                        .HasColumnType("int");

                    b.Property<Guid>("FoodLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Protein")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodLogId");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aac86f05-0ed4-43a1-876f-6ba34f605661"),
                            Calories = 170,
                            Carbs = 0,
                            Fat = 7,
                            FoodLogId = new Guid("da789a67-5481-4ac9-b338-0a9b3c069a1f"),
                            Name = "Tuna",
                            Protein = 26
                        },
                        new
                        {
                            Id = new Guid("fe8e839e-c834-4b88-ab3c-e8fe0610a3f1"),
                            Calories = 356,
                            Carbs = 72,
                            Fat = 2,
                            FoodLogId = new Guid("da789a67-5481-4ac9-b338-0a9b3c069a1f"),
                            Name = "Pasta",
                            Protein = 12
                        },
                        new
                        {
                            Id = new Guid("81b43909-4490-42fe-af1d-f0e952cf727a"),
                            Calories = 325,
                            Carbs = 25,
                            Fat = 3,
                            FoodLogId = new Guid("da789a67-5481-4ac9-b338-0a9b3c069a1f"),
                            Name = "Zbregov Protein",
                            Protein = 50
                        });
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.FoodLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FoodLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("da789a67-5481-4ac9-b338-0a9b3c069a1f"),
                            Date = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("cd6b8714-4806-4fe6-b28f-90185dbfbdd2")
                        });
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.TrainingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TrainingLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb31d06e-13da-4ba0-a923-5c062399f3a8"),
                            Date = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("cd6b8714-4806-4fe6-b28f-90185dbfbdd2")
                        });
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cd6b8714-4806-4fe6-b28f-90185dbfbdd2"),
                            Email = "admin@hotmail.com",
                            Password = "$2b$10$UDdxSGgMvqr.4oKUSsx.O.lDqO4whg8zEfocSTf/DdhNsqU9VlV2q",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.WeightLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WeightLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0faee6ac-1772-4bbe-9990-a7d9a22dd559"),
                            Date = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("cd6b8714-4806-4fe6-b28f-90185dbfbdd2"),
                            Value = 77.5
                        },
                        new
                        {
                            Id = new Guid("c4714153-23fc-4413-b6dc-7fa230cb8883"),
                            Date = new DateTime(2023, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("cd6b8714-4806-4fe6-b28f-90185dbfbdd2"),
                            Value = 78.0
                        },
                        new
                        {
                            Id = new Guid("9d9926f0-ee0b-4cdb-b4bd-c178377d8868"),
                            Date = new DateTime(2023, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("cd6b8714-4806-4fe6-b28f-90185dbfbdd2"),
                            Value = 77.299999999999997
                        },
                        new
                        {
                            Id = new Guid("8514a58d-0edc-46bc-a0c8-bd912b5f5742"),
                            Date = new DateTime(2023, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("cd6b8714-4806-4fe6-b28f-90185dbfbdd2"),
                            Value = 77.599999999999994
                        },
                        new
                        {
                            Id = new Guid("52fce968-8a43-4dbd-ab26-dcf334c149dd"),
                            Date = new DateTime(2023, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("cd6b8714-4806-4fe6-b28f-90185dbfbdd2"),
                            Value = 77.799999999999997
                        });
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.Exercise", b =>
                {
                    b.HasOne("FitnessPathApp.DomainLayer.Entities.ExerciseChoice", "ExerciseChoice")
                        .WithMany("Exercises")
                        .HasForeignKey("ExerciseChoiceId");

                    b.HasOne("FitnessPathApp.DomainLayer.Entities.TrainingLog", "Log")
                        .WithMany("Exercises")
                        .HasForeignKey("TrainingLogId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ExerciseChoice");

                    b.Navigation("Log");
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.FoodItem", b =>
                {
                    b.HasOne("FitnessPathApp.DomainLayer.Entities.FoodLog", "Log")
                        .WithMany("FoodItems")
                        .HasForeignKey("FoodLogId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Log");
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.FoodLog", b =>
                {
                    b.HasOne("FitnessPathApp.DomainLayer.Entities.User", "User")
                        .WithMany("FoodLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.TrainingLog", b =>
                {
                    b.HasOne("FitnessPathApp.DomainLayer.Entities.User", "User")
                        .WithMany("TrainingLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.WeightLog", b =>
                {
                    b.HasOne("FitnessPathApp.DomainLayer.Entities.User", "User")
                        .WithMany("WeightLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.ExerciseChoice", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.FoodLog", b =>
                {
                    b.Navigation("FoodItems");
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.TrainingLog", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.User", b =>
                {
                    b.Navigation("FoodLogs");

                    b.Navigation("TrainingLogs");

                    b.Navigation("WeightLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
