// <auto-generated />
using System;
using FitnessPathApp.DomainLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessPathApp.DomainLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseChoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<Guid>("TrainingLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseChoiceId");

                    b.HasIndex("TrainingLogId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("82a61b04-1cda-4045-abb5-0c1596f9aa36"),
                            ExerciseChoiceId = new Guid("3e165f3d-f9fa-4e27-a5b9-05d3b938d8eb"),
                            Reps = 5,
                            Sets = 5,
                            TrainingLogId = new Guid("cb31d06e-13da-4ba0-a923-5c062399f3a8"),
                            Weight = 100.0
                        },
                        new
                        {
                            Id = new Guid("46aa1ca5-4670-4a38-a840-96204dd0b3a2"),
                            ExerciseChoiceId = new Guid("bde86a6d-9a37-420d-93ca-60d7b02dc7c4"),
                            Reps = 5,
                            Sets = 5,
                            TrainingLogId = new Guid("cb31d06e-13da-4ba0-a923-5c062399f3a8"),
                            Weight = 140.0
                        },
                        new
                        {
                            Id = new Guid("853172d8-26ca-4de1-acc0-b28d753c328f"),
                            ExerciseChoiceId = new Guid("c1769344-dd80-41fe-bbfc-a16df832929b"),
                            Reps = 5,
                            Sets = 3,
                            TrainingLogId = new Guid("cb31d06e-13da-4ba0-a923-5c062399f3a8"),
                            Weight = 180.0
                        },
                        new
                        {
                            Id = new Guid("9d9d6825-98ba-47cf-b137-2f6431a047ca"),
                            ExerciseChoiceId = new Guid("c328e92b-33ff-4863-9397-d53424ca3f5c"),
                            Reps = 8,
                            Sets = 3,
                            TrainingLogId = new Guid("cb31d06e-13da-4ba0-a923-5c062399f3a8"),
                            Weight = 60.0
                        },
                        new
                        {
                            Id = new Guid("e937cea5-99db-4068-96a2-c75fde51df74"),
                            ExerciseChoiceId = new Guid("c328e92b-33ff-4863-9397-d53424ca3f5c"),
                            Reps = 8,
                            Sets = 3,
                            TrainingLogId = new Guid("cb31d06e-13da-4ba0-a923-5c062399f3a8"),
                            Weight = 70.0
                        });
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.ExerciseChoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExerciseType")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExerciseChoices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3e165f3d-f9fa-4e27-a5b9-05d3b938d8eb"),
                            ExerciseType = 0,
                            IsFavorite = true,
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = new Guid("bde86a6d-9a37-420d-93ca-60d7b02dc7c4"),
                            ExerciseType = 0,
                            IsFavorite = true,
                            Name = "Squat"
                        },
                        new
                        {
                            Id = new Guid("c1769344-dd80-41fe-bbfc-a16df832929b"),
                            ExerciseType = 0,
                            IsFavorite = true,
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = new Guid("c328e92b-33ff-4863-9397-d53424ca3f5c"),
                            ExerciseType = 0,
                            IsFavorite = true,
                            Name = "Overhead Press"
                        });
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.FoodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<int>("Carbs")
                        .HasColumnType("int");

                    b.Property<int>("Fat")
                        .HasColumnType("int");

                    b.Property<Guid>("FoodLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Protein")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodLogId");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aac86f05-0ed4-43a1-876f-6ba34f605661"),
                            Calories = 170,
                            Carbs = 0,
                            Fat = 7,
                            FoodLogId = new Guid("da789a67-5481-4ac9-b338-0a9b3c069a1f"),
                            Name = "Tuna",
                            Protein = 26
                        },
                        new
                        {
                            Id = new Guid("fe8e839e-c834-4b88-ab3c-e8fe0610a3f1"),
                            Calories = 356,
                            Carbs = 72,
                            Fat = 2,
                            FoodLogId = new Guid("da789a67-5481-4ac9-b338-0a9b3c069a1f"),
                            Name = "Pasta",
                            Protein = 12
                        },
                        new
                        {
                            Id = new Guid("81b43909-4490-42fe-af1d-f0e952cf727a"),
                            Calories = 325,
                            Carbs = 25,
                            Fat = 3,
                            FoodLogId = new Guid("da789a67-5481-4ac9-b338-0a9b3c069a1f"),
                            Name = "Zbregov Protein",
                            Protein = 50
                        });
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.FoodLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FoodLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("da789a67-5481-4ac9-b338-0a9b3c069a1f"),
                            Date = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("cd6b8714-4806-4fe6-b28f-90185dbfbdd2")
                        });
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.TrainingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TrainingLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb31d06e-13da-4ba0-a923-5c062399f3a8"),
                            Date = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("cd6b8714-4806-4fe6-b28f-90185dbfbdd2")
                        });
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cd6b8714-4806-4fe6-b28f-90185dbfbdd2"),
                            Email = "admin@hotmail.com",
                            Password = "$2b$10$5.eynkHdHLVnxUx34/VK4u3ejx6pQlhpk8iRhW4zd7rDxChhYaYUi",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.WeightLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WeightLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0faee6ac-1772-4bbe-9990-a7d9a22dd559"),
                            Date = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("cd6b8714-4806-4fe6-b28f-90185dbfbdd2"),
                            Value = 77.5
                        },
                        new
                        {
                            Id = new Guid("c4714153-23fc-4413-b6dc-7fa230cb8883"),
                            Date = new DateTime(2023, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("cd6b8714-4806-4fe6-b28f-90185dbfbdd2"),
                            Value = 78.0
                        },
                        new
                        {
                            Id = new Guid("9d9926f0-ee0b-4cdb-b4bd-c178377d8868"),
                            Date = new DateTime(2023, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("cd6b8714-4806-4fe6-b28f-90185dbfbdd2"),
                            Value = 77.299999999999997
                        },
                        new
                        {
                            Id = new Guid("8514a58d-0edc-46bc-a0c8-bd912b5f5742"),
                            Date = new DateTime(2023, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("cd6b8714-4806-4fe6-b28f-90185dbfbdd2"),
                            Value = 77.599999999999994
                        },
                        new
                        {
                            Id = new Guid("52fce968-8a43-4dbd-ab26-dcf334c149dd"),
                            Date = new DateTime(2023, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("cd6b8714-4806-4fe6-b28f-90185dbfbdd2"),
                            Value = 77.799999999999997
                        });
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.Exercise", b =>
                {
                    b.HasOne("FitnessPathApp.DomainLayer.Entities.ExerciseChoice", "ExerciseChoice")
                        .WithMany("Exercises")
                        .HasForeignKey("ExerciseChoiceId");

                    b.HasOne("FitnessPathApp.DomainLayer.Entities.TrainingLog", "Log")
                        .WithMany("Exercises")
                        .HasForeignKey("TrainingLogId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ExerciseChoice");

                    b.Navigation("Log");
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.FoodItem", b =>
                {
                    b.HasOne("FitnessPathApp.DomainLayer.Entities.FoodLog", "Log")
                        .WithMany("FoodItems")
                        .HasForeignKey("FoodLogId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Log");
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.FoodLog", b =>
                {
                    b.HasOne("FitnessPathApp.DomainLayer.Entities.User", "User")
                        .WithMany("FoodLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.TrainingLog", b =>
                {
                    b.HasOne("FitnessPathApp.DomainLayer.Entities.User", "User")
                        .WithMany("TrainingLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.WeightLog", b =>
                {
                    b.HasOne("FitnessPathApp.DomainLayer.Entities.User", "User")
                        .WithMany("WeightLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.ExerciseChoice", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.FoodLog", b =>
                {
                    b.Navigation("FoodItems");
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.TrainingLog", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.User", b =>
                {
                    b.Navigation("FoodLogs");

                    b.Navigation("TrainingLogs");

                    b.Navigation("WeightLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
