// <auto-generated />
using System;
using FitnessPathApp.DomainLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FitnessPathApp.DomainLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220227114123_DefineExerciseAndSeed")]
    partial class DefineExerciseAndSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<Guid>("TrainingLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Exercise");

                    b.HasData(
                        new
                        {
                            Id = new Guid("82a61b04-1cda-4045-abb5-0c1596f9aa36"),
                            Name = "Bench Press",
                            Reps = 5,
                            Sets = 5,
                            TrainingLogId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 100.0
                        },
                        new
                        {
                            Id = new Guid("46aa1ca5-4670-4a38-a840-96204dd0b3a2"),
                            Name = "Squat",
                            Reps = 5,
                            Sets = 5,
                            TrainingLogId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 140.0
                        },
                        new
                        {
                            Id = new Guid("853172d8-26ca-4de1-acc0-b28d753c328f"),
                            Name = "Deadlift",
                            Reps = 5,
                            Sets = 3,
                            TrainingLogId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 180.0
                        },
                        new
                        {
                            Id = new Guid("9d9d6825-98ba-47cf-b137-2f6431a047ca"),
                            Name = "Overhead Press",
                            Reps = 8,
                            Sets = 3,
                            TrainingLogId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 60.0
                        },
                        new
                        {
                            Id = new Guid("e937cea5-99db-4068-96a2-c75fde51df74"),
                            Name = "Barbell Row",
                            Reps = 8,
                            Sets = 3,
                            TrainingLogId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 70.0
                        });
                });

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.WeightLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("WeightLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0faee6ac-1772-4bbe-9990-a7d9a22dd559"),
                            Date = new DateTime(2022, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 77.5
                        },
                        new
                        {
                            Id = new Guid("c4714153-23fc-4413-b6dc-7fa230cb8883"),
                            Date = new DateTime(2022, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 78.0
                        },
                        new
                        {
                            Id = new Guid("9d9926f0-ee0b-4cdb-b4bd-c178377d8868"),
                            Date = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 77.299999999999997
                        },
                        new
                        {
                            Id = new Guid("8514a58d-0edc-46bc-a0c8-bd912b5f5742"),
                            Date = new DateTime(2022, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 77.599999999999994
                        },
                        new
                        {
                            Id = new Guid("52fce968-8a43-4dbd-ab26-dcf334c149dd"),
                            Date = new DateTime(2022, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 77.799999999999997
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
