// <auto-generated />
using System;
using FitnessPathApp.DomainLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FitnessPathApp.DomainLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220224222658_RedefineWeightLogAndSeed")]
    partial class RedefineWeightLogAndSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FitnessPathApp.DomainLayer.Entities.WeightLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("WeightLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0faee6ac-1772-4bbe-9990-a7d9a22dd559"),
                            Date = new DateTime(2022, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 77.5
                        },
                        new
                        {
                            Id = new Guid("c4714153-23fc-4413-b6dc-7fa230cb8883"),
                            Date = new DateTime(2022, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 78.0
                        },
                        new
                        {
                            Id = new Guid("9d9926f0-ee0b-4cdb-b4bd-c178377d8868"),
                            Date = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 77.299999999999997
                        },
                        new
                        {
                            Id = new Guid("8514a58d-0edc-46bc-a0c8-bd912b5f5742"),
                            Date = new DateTime(2022, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 77.599999999999994
                        },
                        new
                        {
                            Id = new Guid("52fce968-8a43-4dbd-ab26-dcf334c149dd"),
                            Date = new DateTime(2022, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 77.799999999999997
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
